CROPPED_SAMPLES_DIR = 'data/cropped_images'
NUM_TRAIN_SAMPLES = 100000
CENTER_SQUARE_RATIO = 0.5
SCALING_SIZE = 64
OUTPUT_SIZE = 64

TRAIN_BATCH_SIZE = 8
TRAIN_SHUFFLE = True
TRAIN_NUM_WORKERS = 4

VAL_BATCH_SIZE = 4
VAL_SHUFFLE = False
VAL_NUM_WORKERS = 2