CROPPED_SAMPLES_DIR = 'data/cropped_images'
NUM_TRAIN_SAMPLES = 100000
CENTER_SQUARE_RATIO = 0.5
SCALING_SIZE = 64
OUTPUT_SIZE = 64

TRAIN_BATCH_SIZE = 8
TRAIN_SHUFFLE = False
TRAIN_NUM_WORKERS = 4

VAL_BATCH_SIZE = 4
VAL_SHUFFLE = False
VAL_NUM_WORKERS = 2
VAL_RATIO = 0.2
NUM_VAL_SAMPLES = 512


NUM_ENCODER_FILTERS = 64
NUM_DECODER_FILTERS = 64
NUM_BOTTLENECK = 4000
NUM_OUTPUT_CHANNELS = 3
